version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:1c0fde6a-20220811
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
      - "3000:3000"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "apt update && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs && npm install --global yarn && cargo build --release && ./target/release/node-template --dev --ws-external"
