apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoblockchain-node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 4
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: genesis_block:latest
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        livenessProbe:
          tcpSocket:
            port: 9944
          initialDelaySeconds: 15
          periodSeconds: 20
        command: ["bash"]
        args: ["-c","/var/www/node-template/node-template --chain local --port 30333 --ws-port 9944 --bootnodes /ip4/172.17.0.3/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp --validator"]
        imagePullPolicy: Never